name: build kernel with WireGuard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout script
        uses: actions/checkout@v4
      
      - name: run build script
        run: |
          chmod +x build.sh
          bash build.sh --wireguard
          
      - name: upload kernel 
        uses: actions/upload-artifact@v4
        with:
          name: release-kernel
          path: |
            AnyKernel3/*
